### ISSUE TITLE
大佬你好 请问可以提供一下efi吗  同款设备

### ISSUE THREAD

**Issue by meko95** [Alex-Zhangzhipeng/ser5pro-hackintosh-bcm94360z4-Monterey#1]

**Comment by Alex-Zhangzhipeng** [comment]
由于noot作者的要求，不能直接提供EFI。而国内网站上，对应的CSDN作者有：https://blog.csdn.net/u012514495/article/details/130957419的11.7.7安装，其EFI完美适配5800h，我的更换了z4网卡，并没有添加intel网卡驱动，建议你使用这个。当然你要使用这个EFI的话，升级12系统要注意两点：1.更新较新nootedred。 2.使用macmini8，1或者 imac 20，1 smbios，macpro会黑屏。我的是macmini使用成功，而此处作者：https://bbs.pcbeta.com/viewthread-1970297-1-1.html的是imac 20，1.而我使用imac20，1会出现鼠标无法使用的问题，你可以参考一下。

**Comment by Alex-Zhangzhipeng** [comment]
当然，如果你使用的为z4网卡，可以留下你的邮箱，我给你发送一份即可

**Comment by meko95** [comment]
嗯嗯 感谢。这个csdn上的我昨晚试过了，安装的时候会直接进入英文的recovry，然后就一直转圈圈，我今晚再试一下

**Comment by Alex-Zhangzhipeng** [comment]
可以检查一下secure boot和fast boot

**Comment by meko95** [comment]
安装上了，但是会偶尔出现十几秒卡死，过一会就又好了。原因不明

**Comment by Alex-Zhangzhipeng** [comment]
11.7系统建议更新较新的nootedred驱动，并加上AmdTscSync驱动
[AmdTscSync.kext.zip](https://github.com/Alex-Zhangzhipeng/ser5pro-hackintosh-bcm94360z4-Monterey/files/11753438/AmdTscSync.kext.zip)
[NootedRed.kext.zip](https://github.com/Alex-Zhangzhipeng/ser5pro-hackintosh-bcm94360z4-Monterey/files/11753442/NootedRed.kext.zip)

**Comment by Alex-Zhangzhipeng** [comment]
加上驱动之后需要到config.plist中更新，原作者建议使用1G以上显存，ser5pro设置应该是默认3G，就不需要更改。

**Comment by meko95** [comment]
感谢，感谢👍🏻
